version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    ports:
      - '${APP_PORT:-8000}:8000'
      - '${APP_SSL_PORT:-8443}:443'
    environment:
      - APP_ENV=local
      - APP_KEY=base64:QQQQyhq8ba8iXBPtpLYdMWGPLrzk+v+f0ARYtHpxk0s=
      - APP_DEBUG=true
      - 'DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@mariadb:3306/${DB_DATABASE}?serverVersion=10.6'
    volumes:
      - ./:/var/www/app
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: linuxserver/mariadb:latest
    # ports:
    #   - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_USER: '${DB_USERNAME:-laravel}'
      MYSQL_PASSWORD: '${DB_PASSWORD-laravel}'
      MYSQL_DATABASE: '${DB_DATABASE-laravel}'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5

  phpmyadmin:
    image: linuxserver/phpmyadmin:latest
    ports:
      - '${APP_DB_ADMIN_PORT:-8001}:80'
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 256M
    links:
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - phpmyadmin-data:/var/www/html

volumes:
  db-data:
  phpmyadmin-data:
